GET http://localhost:3001/posts/byfriends/2019-6-31-15-00 
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ik1pa3NhIiwiaWQiOiI1ZDMyZjc0ZjUwMzkzNjIyZTg4MWU2YzAiLCJpYXQiOjE1NjQ1MTU2MDF9.EX0dvY9k3lA1FeSUma-8AafWVLDM-55yr0elNyvcrIU


