POST http://localhost:3001/posts
Content-type: application/json

{
  "content": "This is a test post. NOW IT SHALL WORK!",
  "picture": "",
  "likes": 0,
  "user": "5d15a14fbc41a81d7c1b718e",
  "comments": []
}